### ISSUE TITLE
Prev/Next Links are strange

### ISSUE THREAD

**Issue by guettli** [prometheus-operator/website#29]
I am at the bottom of [Compatibility](https://prometheus-operator.dev/docs/operator/compatibility/)

The prev/next links at the bottom are strange:

![image](https://user-images.githubusercontent.com/414336/164992772-b9d3c1bf-7e8c-4388-96fa-7c3352061dc5.png)

**Comment by paulfantom** [comment]
Yeah, that's because `Compatibility` is sourced from `prometheus-operator` and not from `prologue`. Seems like an issue in how we categorize pages.

Thanks for reporting this! If you have more issues regarding usage of prometheus-operator, join us on kubernetes slack in #prometheus-operator channel.

**Comment by simonpasquier** [comment]
It seems to be fixed now

![image](https://user-images.githubusercontent.com/2587585/192821548-43d55a00-04f4-45cd-a89b-37bd34e70424.png)

**Comment by guettli** [comment]
yes, I can confirm. Looks good now. Thank you!
